### PR TITLE
Show commits before update, use regex patterns for breaking changes 

### PR DESCRIPTION
**Pull request by LeonHeidelbach**
While updating several times today I felt like seeing the list of commits before applying them would be very useful, so I added another overview. I have also switched to using regular expression based pattern matching for finding breaking changes. There was also a bug that if you had multiple buffers open, would close the current buffer if no updates were found.

### CODE REVIEW

**Comment by LeonHeidelbach** [comment]
@siduck could you have a quick look at this? 👀

**Comment by siduck** [comment]
> @siduck could you have a quick look at this? eyes

looks good, btw can you use a whole window for the update feature? when there are many commits, It'd  have less space imo 

image

**Comment by LeonHeidelbach** [comment]
> > @siduck could you have a quick look at this? eyes
> 
> 
> 
> looks good, btw can you use a whole window for the update feature? when there are many commits, It'd  have less space imo or use a large floating window like packer o_o
> 
> 
> 
> image
> 
> 

I would have to look into how spawning popup windows like packer does works, but sure that would also be an option. The only thing is, that I think this would be quite intrusive. Can you not scroll the echoed messages once the list gets longer? I haven't tried it with that many commits.

**Comment by siduck** [comment]
I think it should be scrollable like the :help buffer

**Comment by LeonHeidelbach** [comment]
Well I mean we could offer an option to the user to choose between echoing changes or displaying them in a separate buffer. I will look into the workings of spawning popups if you like. Could you merge this PR for now though? 👀😬

**Comment by siduck** [comment]
@LeonHeidelbach the updater feels a bit slow at the start, like when i press leader uu, i have to wait for 5-6 secs and then it prints the fetching new changes message ;(

**Comment by LeonHeidelbach** [comment]
> @LeonHeidelbach the updater feels a bit slow at the start, like when i press leader uu, i have to wait for 5-6 secs and then it prints the fetching new changes message ;(

@siduck That's because we are doing network stuff before printing the first status message (i.e. "Fetching from remote…"). Before fetching the actual changes from the repo, I check the remote HEAD with 'git ls-remote'. I could print a status message like "Checking for updates" right at the start so that there will be no confusion.

**Comment by siduck** [comment]
> > @LeonHeidelbach the updater feels a bit slow at the start, like when i press leader uu, i have to wait for 5-6 secs and then it prints the fetching new changes message ;(
> 
> @siduck That's because we are doing network stuff before printing the first status message (i.e. "Fetching from remote…"). Before fetching the actual changes from the repo, I check the remote HEAD with 'git ls-remote'. I could print a status message like "Checking for updates" right at the start so that there will be no confusion.

yea add that

**Comment by siduck** [comment]
can you print the progress as in %?

**Comment by siduck** [comment]
would be cool :0

**Comment by LeonHeidelbach** [comment]
> can you print the progress as in %?

Well, I could if there was a way to clear the previously echoed messages. Somehow ` utils.clear_cmdline()` does not seem to do the trick. If you know how I can do that, I will implement progess percentages.

**Comment by LeonHeidelbach** [comment]
> > > @LeonHeidelbach the updater feels a bit slow at the start, like when i press leader uu, i have to wait for 5-6 secs and then it prints the fetching new changes message ;(
> > 
> > 
> > @siduck That's because we are doing network stuff before printing the first status message (i.e. "Fetching from remote…"). Before fetching the actual changes from the repo, I check the remote HEAD with 'git ls-remote'. I could print a status message like "Checking for updates" right at the start so that there will be no confusion.
> 
> yea add that

Done

> can you print the progress as in %?

And done as well! https://github.com/NvChad/extensions/pull/16

**Pull request merged**
