### PR TITLE
No more 'git reset --hard' update (just rebase to keep your mod)

### PR DESCRIPTION
**Pull request by osamuaoki**
This is meant to be applied on top of PR https://github.com/NvChad/extensions/pull/1
and touching `lua/nvchad/update_nvchad.lua`.

After several iteration, I realize committing all cached and working tree change and pull --rebase is all we need.

With this, you can even make changes beyond chadrc file somewhat safely (with common sense and guarding lines to avoid merge conflict etc.)  Merge conflict is easy to resolve too.

This makes it easy to add extra packages etc since there is no more RESET!

For example, I now have Debian graphics as my dashboard graphics.

I can now track your repo as READ-only origin while pushing my local changes to my github account.   So I don't worry which backup configuration is which etc.

### CODE REVIEW

**Comment by siduck76** [comment]
@Akianonymus look upon this.

**Comment by osamuaoki** [comment]
One note:
I am assuming that the chadrc in repo doesn't change in my current PR since it hasn't been updated when default_config got few more lines.
If we need to allow the change to chadrc, few more lines needs to be added.

Let me know.  (I am busy learning how exactly you the whole NvChad is structured by doing opposite of fancy recent refactoring.)

Basically, this script should go as

* commit all pending staged changes to local repo (commit)
* commit all working tree changes to local repo (commit -a)
* Get hash_before to revert in case of trouble
* [**NEW**] checkout chadrc from origin/main and commit
* pull --rebase
* if non clean, roll back to hash_before with reset --hard
* [**NEW**] checkout chadrc from hash_before

**Comment by G-Rowell** [comment]
Hey @osamuaoki,

I really like this!

I've been super busy with uni & work,
so I'll test this out very soon, but I do like the idea.

I'll get back to you after my testing as soon as I can!

Thanks for the PR


G

**Comment by osamuaoki** [comment]
No rush and no problem.

FYI: I am plying with doom-nvim now.  It's similar but its adoption of which-key makes it easy to make  key-bindings more accessible and self documenting.  (I understand it looks a bit of bloat.  But it avoids slowdown by using vim.defer-fn a lot.)  I may try the similar there.)

**Comment by siduck76** [comment]
@osamuaoki we will soon have whichkey or nvim-mapper soon too :)

**Comment by Akianonymus** [comment]
Some improvements regarding this

No need to check for chadrc

What to do

Check if the config directory is a git

**Comment by siduck** [comment]
> Some improvements regarding this
> 
> No need to check for chadrc
> 
> What to do
> 
> Check if the config directory is a git directory
> 
> Store current sha in a variable, assuming old
> 
> If any uncommitted changes, then create a commit for those
> 
> Store the current sha in another variable, assuming new
> 
> Now git reset --hard to old sha
> 
> Try to pull, if pull is successful, then git commit -n new ( new is sha saved before ) and then run git reset ( so that the git still shows the unstaged files )
> 
> If pull is not successful, then git reset --hard old ( old is sha saved the first time ) and then run git reset ( so that the git still shows the unstaged files )
> 
> This is a basic overview, feel free to ask if any confusion

@osamuaoki

**Pull request closed without merging**
