### PR TITLE
Check for breaking changes before updating NvChad/NvChad#984

### PR DESCRIPTION
**Pull request by LeonHeidelbach**
This adds the feature discussed in NvChad/NvChad#984 to :NvChadUpdate.

### CODE REVIEW

**Comment by siduck** [comment]
@LeonHeidelbach can you add this feature too?

https://github.com/NvChad/NvChad/issues/825

**Comment by LeonHeidelbach** [comment]
> @LeonHeidelbach can you add this feature too?
> 
> 
> 
> https://github.com/NvChad/NvChad/issues/825

Sure I mean I basically already did, I only filtered the commit list by breaking changes. I will look into it a little later today and create a PR. @siduck Any thoughts on letting users alter the keyword list for breaking changes? Or do you have other specific keywords that you would like to only use in your commit messages when changes specifically break configs? This would prevent users from seeing the list of "potentially breaking changes" too frequently.

**Comment by siduck** [comment]
i'll just use break keyword in commits for alerting breaking changes from now

**Comment by LeonHeidelbach** [comment]
Okay. So would you like me to cut the list of keywords down to "break" only then?

**Comment by siduck** [comment]
> Okay. So would you like me to cut the list of keywords down to "break" only then?

put it to breaking_change , we sometimes use break in commits

**Comment by LeonHeidelbach** [comment]
> > Okay. So would you like me to cut the list of keywords down to "break" only then?
> 
> 
> 
> put it to breaking_change , we sometimes use break keyword in commits for non breaking changes too

Will do. If anything changes later on, you can just adjust the keyword list yourself.

**Pull request merged**
