### PR TITLE
Create User AutoCommand Event on theme reload

### PR DESCRIPTION
**Pull request by shaun-mathew**
Added User AutoCommand NvChadThemeReload so that users can listen for this event on theme reload.

### Demonstration of Feature:

nvchad_reload

### CODE REVIEW

**Comment by siduck** [comment]
@shaun-mathew does this work? 

```lua
vim.api.nvim_exec_autocmds("User", { pattern = " NvChadThemeReload" })
```

if yes then update the PR!

**Review by shaun-mathew — COMMENTED** [review]
Change to vim.api call works!

**Comment by siduck** [comment]
wait, what are you trying to do with this event in your custom config?

**Comment by shaun-mathew** [comment]
For right now, changing kitty terminal background in response to NvChad colorscheme change.

**Comment by siduck** [comment]
> For right now, changing kitty terminal background in response to NvChad colorscheme change.

oh cool then we could basically control whole system theme whenever switching themes :0

**Comment by siduck** [comment]
Also set padding to 0 when inside nvim and add padding back when leaving nvim, this can be done by using autocmds 

 check https://github.com/siduck/st/issues/39#issuecomment-1192686747

**Comment by UTFeight** [comment]
> **Note** There was some issues about the script noted above so check [this](https://github.com/siduck/st/issues/39#issuecomment-1637153332) out

**Pull request merged**
